### ISSUE TITLE
Singularity without sudo

### ISSUE THREAD

**Issue by phuicy** [singularityhub/jupyter#2]
Could jupyter not be run as non-root and a bind path used for file saving?

**Comment by vsoch** [comment]
I've tested jupyter in Singularity using [containershare](https://github.com/vsoch/containershare) and I've found that:

1. if you provide files in the container for the user to start with, this means you can't mount and while they can open them, the saving needs to happen elsewhere
2. If you provide a vanilla notebook and start it in a mounted directory with write, you should be able to save ok.

In **both** cases you can actually do a File --> Save As sort of deal, and download something locally, so there are good solutions here!

What you can't logically do, given a read only container, is write a file **into**  it. The choices are file system that is mounted with write, or local machine.

**Comment by phuicy** [comment]
Where is this image?

**Comment by vsoch** [comment]
If you read the README for the containershare that I linked, there are several resources offered to you:

 - the link to the repos that builds (a number of jupyter backend) containers: https://github.com/vsoch/containershare#container-repository-templates
 - web interfaces to all of the above https://vsoch.github.io/containershare

Each containershare container template has a full tutorial in their respective READMEs and interfaces, and links to the tagged images on Docker Hub. I think you'll find if you read things it's all there.

**Comment by phuicy** [comment]
Sorry, I don't see how these help at all.

I would like to run

```
singularity run --B ~/notebooks:/opt/notebooks jupyter.img
```

**Comment by vsoch** [comment]
If you use Docker, just use the containers as they are shown. If you use Singularity, you can use the forward tool (or just the docker container URI with Singularity). But it's not ideal because it will likely start a ghost process on port 8888.

**Comment by vsoch** [comment]
And I'll be more explicit since you are having trouble looking at the scripts and copy pasting the command:

```bash
singularity exec --home "${HOME}" --bind ${HOME}/.local:/home/joyvan/.local docker://vanessa/repo2docker-conda jupyter notebook --no-browser --port=9998 --ip 0.0.0.0
```

You will likely need to tweak around with --pwd and what is mounted to control write, I will leave this up to you to figure out, I believe in you!! lol.

**Comment by phuicy** [comment]
What do you mean use docker? I can't use docker on the servers, I can use docker images. 
On the hpc, if i install conda locally i can run jupyter notebook. I would like to do the same with singularity.

If I have to run Singularity with sudo, whats the point in it?

**Comment by vsoch** [comment]
Did you not see my last comment? The one with the singularity command...

**Comment by phuicy** [comment]
Aah no, it hadn't updates

**Comment by phuicy** [comment]
Ok, so your kind suggestions did not help, actual answer:
```
 export XDG_RUNTIME_DIR=""
```
in the script.

**Comment by vsoch** [comment]
But your kindness on the other hand... wow!

**Comment by phuicy** [comment]
Yeah, sorry. Like 14 hours of crap laggy VNC to ssh to failing docker install had me at the end of my tether. Thanks for your quick help.
