### ISSUE TITLE
--writable doesn't work to create the image file

### ISSUE THREAD

**Issue by RGD2** [singularityhub/jupyter#3]
Seems to be because of the newer version of singularity I have.

Changing that line to `sudo singularity build --sandbox jupyter.img/ Singularity` does the trick.
Note, still need the `--writable` flag on run, like so:

`vagrant@vagrant:~/jupyter$ sudo singularity run -w jupyter.img/ Singularity`

**Comment by vsoch** [comment]
Yes, this repository is definitely dated to an older version, it's hard to keep up with the Singularity release schedule!

Would you care to PR to make the adjustment?

**Comment by vsoch** [comment]
And for the run, you don't need the recipe anymore right? Just:

```bash
sudo singularity run -w jupyter.img/
```

**Comment by RGD2** [comment]
Thanks, good point. 
I didn't expect you to have this fixed so quickly!
